# helmfile.yaml

repositories:
  # - name: apache-airflow
  #   url: https://airflow.apache.org
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: strimzi
    url: https://strimzi.io/charts/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
  # ────────────────────────────────────────
  # 1) Ingress-NGINX
  - name: ingress
    namespace: kafka-kube-ml
    chart: ingress-nginx/ingress-nginx
    values:
      - k8s/ingress-nginx/values.yaml
    set:
      - name: controller.service.type
        value: NodePort
      - name: controller.service.nodePorts.http
        value: 30080
      - name: controller.service.nodePorts.https
        value: 32443
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - k8s/kafka-namespace.yaml
  # ────────────────────────────────────────
  # 2) Apache Airflow
    # - name: airflow
    #   namespace: kafka-kube-ml
    #   chart: apache-airflow/airflow
    #   version: 1.18.0
    #   values:
    #     - extraEnv: |
    #         - name: AIRFLOW_VAR_NAMESPACE
    #           value: "{{ .Namespace }}"
    #         - name: KAFKA_BROKER
    #           value: kafka-cluster-kafka-bootstrap.kafka-stream.svc:9092
    #         - name: KAFKA_TOPIC
    #           value: user-interactions
    #         - name: PARQUET_DIR 
    #           value: /data/parquet
    #         - name: BATCH_SIZE 
    #           value: "100"
    #     - k8s/airflow/values.yaml
    #     - scheduler:
    #         enabled: true
    #       worker:
    #         enabled: true
    #       triggerer:
    #         enabled: true
    #   hooks:
    #     - events: ["presync"]
    #       showlogs: true
    #       command: kubectl
    #       args:
    #         - apply
    #         - -f
    #         - k8s/airflow/airflow-dags-pvc.yaml
    #         - -n
    #         - kafka-kube-ml
    #     - events: ["postsync"]
    #       showlogs: true
    #       command: kubectl
    #       args:
    #         - patch
    #         - ingress
    #         - airflow-ingress
    #         - -n
    #         - kafka-kube-ml
    #         - --type=json
    #         - -p
    #         - '[{"op": "add", "path": "/spec/ingressClassName", "value":"nginx"}]'
  # ────────────────────────────────────────
  # 3) Strimzi Kafka Operator
  - name: kafka-operator
    namespace: kafka-stream
    chart: strimzi/strimzi-kafka-operator
    version: 0.45.1
    createNamespace: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          # - k8s/kafka/kafka-cluster.yaml
          - k8s/kafka/kraft/kafka-cluster.yaml
          - -n
          - kafka-stream
      - events: ["postsync"]            # <-- apply the topic after operator/cluster
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - k8s/kafka/kafkatopic-user-interactions.yaml
          - -n
          - kafka-stream
  # 5) PVC for Kafka Consumer
  - name: stream-processor
    namespace: kafka-kube-ml
    chart: ./k8s/charts/stream-processor
    values:
      # - image:
      #     repository: awesomeplant/stream_processor
      #     tag: latest
      - flushIntervalSeconds: 5
      - batchSize: 50
      - output:
          tmpDir: /tmp
    hooks:
      - events: ["presync"]
        command: sh
        args:
          - -c
          - |
            set -e
            kubectl -n kafka-stream wait --for=condition=Ready kafka/kafka-cluster --timeout=10m
            until kubectl -n kafka-stream get svc kafka-cluster-kafka-bootstrap >/dev/null 2>&1; do sleep 3; done
  - name: user-simulator
    namespace: kafka-kube-ml
    chart: ./k8s/charts/user-simulator
    values:
      - generator:
          rate: 100
          metricsPort: 8000
        kafka:
          brokers: kafka-cluster-kafka-bootstrap.kafka-stream.svc:9092
          topic: user-interactions
    hooks:
      - events: ["presync"]
        command: sh
        args:
          - -c
          - |
            set -e
            kubectl -n kafka-stream wait --for=condition=Ready kafka/kafka-cluster --timeout=10m
            until kubectl -n kafka-stream get svc kafka-cluster-kafka-bootstrap >/dev/null 2>&1; do sleep 3; done
hooks:
  - events: ["prepare"]
    showlogs: true
    command: kubectl
    args:
      - apply
      - -f
      - k8s/consumer/consumer-pvc.yaml
      - -n
      - kafka-kube-ml
