# helmfile.yaml

repositories:
  - name: apache-airflow
    url: https://airflow.apache.org
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: strimzi
    url: https://strimzi.io/charts/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
  # ────────────────────────────────────────
  # 1) Ingress-NGINX
  - name: ingress
    namespace: kafka-kube-ml
    chart: ingress-nginx/ingress-nginx
    values:
      - k8s/ingress-nginx/values.yaml
    set:
      - name: controller.service.type
        value: NodePort
      - name: controller.service.nodePorts.http
        value: 30080
      - name: controller.service.nodePorts.https
        value: 32443
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - k8s/kafka-namespace.yaml
  # ────────────────────────────────────────
  # 2) Apache Airflow
  - name: airflow
    namespace: kafka-kube-ml
    chart: apache-airflow/airflow
    version: 1.18.0
    values:
      - extraEnv: |
          - name: AIRFLOW_VAR_NAMESPACE
            value: "{{ .Namespace }}"
          - name: KAFKA_BROKER
            value: kafka-cluster-kafka-bootstrap.kafka-stream:9092
          - name: KAFKA_TOPIC
            value: user-interactions
          - name: PARQUET_DIR 
            value: /data/parquet
          - name: BATCH_SIZE 
            value: "100"
      - k8s/airflow/values.yaml
      - scheduler:
          enabled: true
        worker:
          enabled: true
        triggerer:
          enabled: true
    hooks:
      - events: ["presync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - k8s/airflow/airflow-dags-pvc.yaml
          - -n
          - kafka-kube-ml
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - patch
          - ingress
          - airflow-ingress
          - -n
          - kafka-kube-ml
          - --type=json
          - -p
          - '[{"op": "add", "path": "/spec/ingressClassName", "value":"nginx"}]'
  # ────────────────────────────────────────
  # 3) Strimzi Kafka Operator
  - name: kafka-operator
    namespace: kafka-stream
    chart: strimzi/strimzi-kafka-operator
    version: 0.45.1
    createNamespace: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - k8s/kafka/kafka-cluster.yaml
          - -n
          - kafka-stream
  # ────────────────────────────────────────
  # 4) Kubernetes Dashboard
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 6.0.8
    createNamespace: true
    values:
      - fullnameOverride: dashboard
      - serviceAccount:
          create: true
          name: admin-user
      - ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hosts:
            - dashboard.local
          paths:
            - /
          pathType: Prefix
      - extraArgs:
          - --enable-skip-login
          - --enable-insecure-login
      - protocolHttp: false
      - protocolHttps: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - create
          - clusterrolebinding
          - admin-user
          - --clusterrole=cluster-admin
          - --serviceaccount=kubernetes-dashboard:admin-user
  # 5) PVC for Kafka Consumer
  # This step ensures the PVC is created for the Python Kafka Consumer to write parquet files.
  # - name: consumer-parquet-pvc
  #   namespace: kafka-kube-ml
  #   chart: "bitnami/common" # dummy chart just to run the hook, won't actually install anything
  #   version: 2.7.1
  #   disableValidationOnInstall: true
hooks:
  - events: ["prepare"]
    showlogs: true
    command: kubectl
    args:
      - apply
      - -f
      - k8s/consumer/consumer-pvc.yaml
      - -n
      - kafka-kube-ml
