executor: LocalExecutor

airflowImage:
  repository: apache/airflow
  tag: 2.9.1

airflow:
  extraPipPackages:
    - apache-airflow-providers-cncf-kubernetes==7.7.0 #this is incorrect

createUserJob:
  useHelmHooks: false

postgresql:
  enabled: true

redis:
  enabled: true

webserver:
  enabled: true
  service:
    type: NodePort

worker:
  extraVolumeMounts:
    - name: parquet-data
      mountPath: /data/parquet
  extraVolumes:
    - name: parquet-data
      persistentVolumeClaim:
        claimName: consumer-parquet-pvc

ingress:
  enabled: true
  web:
    enabled: true
    ingressClassName: nginx           # <- Critical: set ingress class for web UI
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - name: localhost
    tls:
      enabled: false
  api:
    enabled: true
    ingressClassName: nginx           # <- Critical: set ingress class for API
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - name: localhost
    tls:
      enabled: false

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc

config:
  core:
    dag_dir_list_interval: 30

# env:
#   - name: AIRFLOW_NAMESPACE
#     value: '{{ .Values.env.AIRFLOW_NAMESPACE | quote }}''
