apiVersion: v1
kind: PersistentVolume
metadata:
  name: consumer-parquet-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/Users/temp/parquet_dir/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-parquet-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: consumer-parquet-pv
